FROM python:3.13-slim

# Build-Argument für GitHub URL
ARG GITHUB_URL
ARG WEBHOOK_URL

# Als Umgebungsvariable setzen, damit sie im Container verfügbar ist
ENV GITHUB_URL=${GITHUB_URL}
ENV WEBHOOK_URL=${WEBHOOK_URL}

RUN apt-get update && apt-get install -y \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY startup_streamlit.sh /app/startup_streamlit.sh
RUN chmod +x /app/startup_streamlit.sh

CMD ["/app/startup_streamlit.sh"]

