FROM docker.n8n.io/n8nio/n8n:latest
ARG GITHUB_URL
ENV GITHUB_URL=${GITHUB_URL}

USER root
RUN apk add --no-cache curl

WORKDIR /app

COPY init-workflows.sh /app/init-workflows.sh
RUN chmod +x /app/init-workflows.sh \
    && chown node:node /app/init-workflows.sh

CMD ["/app/init-workflows.sh"]